modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"
issueTrackerURL="https://github.com/affehund/ForgottenRecipes/issues" #optional
[[mods]] #mandatory
modId="forgottenrecipes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Forgotten Recipes" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Affehund/ForgottenRecipes/main/update.json" #optional
displayURL="https://curseforge.com/minecraft/mc-mods/forgottenrecipes-fabric" #optional
logoFile="logo.png" #optional
authors="Affehund" #optional
description='''
Adding recipes that should be in minecraft 1.17
'''

